### ISSUE TITLE
Error when running 'gulp'

### ISSUE THREAD

**Issue by pfeiferchristopher** [rynocouse/laravel-elixir-compass#8]
Hello! I'm very excited to be able to use compass with my gulp, elixir, and laravel. However, I after running `npm install` and having `"laravel-elixir-compass": "*"` in my dependencies I receive the following error when initializing gulp:
```bash
Error: Cannot find module 'laravel-elixir/ingredients/helpers/utilities'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/node_modules/laravel-elixir-compass/index.js:4:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
This is my `package.json`
```json
"devDependencies": {
    "gulp": "^3.8.10",
    "laravel-elixir": "*",
      "gulp-sass": "*",
    "laravel-elixir-compass": "*"
  }
```

**Comment by JoeCianflone** [comment]
@rynocouse Can you push the latest code over to npm?  This issue has been fixed already.

@pfeiferchristopher the bug is fixed in master, if you need this ASAP, you might want to install from master:

```npm install git://github.com/rynocouse/laravel-elixir-compass.git -save```

**Comment by pfeiferchristopher** [comment]
I did what you said to install from master and am still having the same error.

**Comment by mattrmiller** [comment]
Same issue for me. Even after posted solution.

**Comment by mattrmiller** [comment]
It appears it is because the laravel-elixer module changed the directory from "helpers" to "commands"

**Comment by thiduzz** [comment]
Yes, temporarily i locally changed the index.js of this package since i only use this package in Development env. just rename the following lines and it works perfectly


    utilities = require('laravel-elixir/ingredients/commands/utilities'),
    Notification = require('laravel-elixir/ingredients/commands/Notification'),

**Comment by darkwinternight** [comment]
Can you fix it and push it over to npm?

**Comment by jbrooksuk** [comment]
I've got a PR open for this.

**Comment by rmariuzzo** [comment]
This issue is taking longer than usual to be fixed, what needs to be done? I'm willing to offer my help on this and get it fixed.

**Comment by jbrooksuk** [comment]
@rmariuzzo I've already done it #14 just needs @rynocouse to merge.

**Comment by rmariuzzo** [comment]
Thansk @jbrooksuk !

**Comment by JoeCianflone** [comment]
I've sent an email to @rynocouse sorry this is taking so long to get pushed up to npm.

**Comment by JoeCianflone** [comment]
OK, I've grown tired of waiting for @rynocouse to respond to email or to issues in this repository (and I need the fixed code too).  I've forked master, fixed the error and pushed this up to npmjs under a different repo.  I need this for my own projects so I'll happily maintain it (and if anyone wants to help please shoot me an email).  

You can find the repo here: https://github.com/JoeCianflone/laravel-elixir-sass-compass
the npm link here: https://www.npmjs.com/package/laravel-elixir-sass-compass
to install it should just be `npm install laravel-elixir-sass-compass`

I'm going to go through any open pull requests in here and see if I can bring them over.

**Comment by jbrooksuk** [comment]
Good work, thanks @JoeCianflone.

**Comment by Ali-Mijo** [comment]
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (C:\Users\lenovo\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:193:16)
    at module.exports (C:\Users\lenovo\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)
